version: "2"

run:
  timeout: 2m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
