name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.21
          cache: false

      - name: Install tools
        run: |
          ./setup.sh
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Lint
        run: mage -v lint

      - name: Test
        run: mage -v test

      - name: Build
        run: mage -v build
