name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: false

      - name: Install tools
        run: |
          ./setup.sh
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Check License Headers
        run: mage -v checkLicenseHeaders

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Test
        run: mage -v test

      - name: Build
        run: mage -v build
